### PR TITLE
feat(): add link to typescript client

### PR DESCRIPTION
**Pull request by jakiestfu**
I created a TS client that leverages the protobuff generated files of this repo. Figured I'd share a link. The CLI was mirrored after the Python Client as well.

### CODE REVIEW

**Comment by jakiestfu** [comment]
@dmarx Any interest in merging this?

**Comment by cruhl** [comment]
https://github.com/Stability-AI/awesome-stability/blob/main/README.md

^ Just created this, I listed `stability-ts` under "community links"

**Comment by chigozienri** [comment]
Thanks @jakiestfu for this, nice work! Apologies for taking so long to respond.

I see @cruhl has already added this to a separate list, but we could add it to a community-contributed section of the readme, if you would be happy with that.

**Pull request closed without merging**
