### PR TITLE
Upgrade protobuf and grpcio

### PR DESCRIPTION
**Pull request by noamt**
As mentioned in issue #176 , the SDK cannot be used with Python 3.11.

This PR:

- Upgrades to the latest version of grpc
- Upgrades to the latest version of protobuf
- Adds 3.11 to the build matrix

### CODE REVIEW

**Review by rvorias — APPROVED** [review]
Tested locally, everything worked.

**Comment by hnykda** [comment]
Great progress on getting stability run on M2 Macbook. However, we need to go further, as I am getting: https://github.com/grpc/grpc/issues/32306

**Review by palp — APPROVED** [review]
Looks good, thank you!

**Comment by palp** [comment]
Merged in #209

**Pull request closed without merging**
