### PR TITLE
Fix client type hinting issues

### PR DESCRIPTION
**Pull request by sayanarijit**
Also minor improvements related to development workflow.

### CODE REVIEW

**Comment by sayanarijit** [comment]
Sorry, I missed disabling the auto formatter before making changes in client.py. I hope it's still readable.

**Comment by sayanarijit** [comment]
Also fixes https://github.com/Stability-AI/stability-sdk/issues/48

**Comment by sayanarijit** [comment]
Fixed conflicts.

**Review by dmarx — APPROVED** [review]

**Comment by dmarx** [comment]
thanks!

**Pull request merged**
